[tool.poetry]
name = "serenade"
version = "0.1.0"
description = "TBD"
authors = ["amir, verumlotus"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
langchain = "^0.0.82"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
