import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import FlowerTop from "../../public/flowers.png";
import styles from "@/styles/Home.module.css";
import { SeparateImage } from "../components/SeparateImage";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Sweet Serenade</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="w-full flex justify-center items-center">
                <SeparateImage image={FlowerTop} alt="Flowers" width={1391} height={287} className="top-0 " />
            </div>
            <main className={styles.main}>
                <h1 className={styles.title}>️Sweet Serenade</h1>
                <p>
                    <i>
                        Tell your crush you like them with{" "}
                        <a href="https://en.wikipedia.org/wiki/Zero_knowledge#:~:text=Zero%20knowledge%20may%20mean%3A,the%20veracity%20of%20the%20statement">
                            zero-knowledge
                        </a>
                    </i>
                </p>

                <div className="py-4"></div>

                <h3 className="font-bold">How this works</h3>
                <p className="text-center">Upload</p>

                <div className="py-4"></div>
                <footer className={styles.footer}>
                    Built by <a href="https://twitter.com/amirbolous">Amir</a> and{" "}
                    <a href="https://twitter.com/verumlotus">verumlotus</a> and{" "}
                    <a href="https://github.com/amirgamil/zk-crush">open source</a> on Github
                </footer>
            </main>
        </div>
    );
}
